{{- if .Values.cleanupJob.enabled }}
{{ $kind := "" }}
{{ $kindBinding := "" }}
{{- if .Values.currentNamespaceOnly }}
{{- $kind        = "Role" }}
{{- $kindBinding = "RoleBinding" }}
{{- else }}
{{- $kind        = "ClusterRole" }}
{{- $kindBinding = "ClusterRoleBinding" }}
{{- end }}
{{- $fullName := include "kube-botblocker-operator.cleanupJob.name" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $kind }}
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "kube-botblocker-operator.cleanupJob.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - kube-botblocker.github.io
    resources:
      - ingressconfigs
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $kindBinding }}
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "kube-botblocker-operator.cleanupJob.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "kube-botblocker-operator.cleanupJob.serviceAccountName" . }}
roleRef:
  kind: {{ $kind }}
  name: {{ $fullName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
