{{- if and .Values.cleanupJob.enabled }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: {{ include "kube-botblocker-operator.cleanupJob.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- with .Values.cleanupJob.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "kube-botblocker-operator.cleanupJob.labels" . | nindent 4 }}
    {{- with .Values.cleanupJob.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
