version: 2
project_name: kube-botblocker
before:
  hooks:
    - go mod tidy
changelog:
  use: github-native
builds:
  - id: kube-botblocker
    binary: kube-botblocker
    main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
