# This rule is not used by the project kube-botblocker itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the kube-botblocker.github.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-botblocker
    app.kubernetes.io/managed-by: kustomize
  name: ingressconfig-editor-role
rules:
- apiGroups:
  - kube-botblocker.github.io
  resources:
  - ingressconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kube-botblocker.github.io
  resources:
  - ingressconfigs/status
  verbs:
  - get
