---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kube-botblocker.github.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kube-botblocker.github.io
  resources:
  - ingresses/finalizers
  verbs:
  - update
- apiGroups:
  - kube-botblocker.github.io
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update
