{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-botblocker-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-botblocker-operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.metrics.port }}
      protocol: TCP
      name: metrics
  selector:
    {{ include "kube-botblocker-operator.selectorLabels" . | nindent 4}}
{{- end }}