{{- if and .Values.currentNamespaceOnly .Values.rbac.enable }}
{{ $fullName := include "kube-botblocker-operator.fullname" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "kube-botblocker-operator.labels" . | nindent 4 }}
  name: {{ $fullName }}
rules:
- apiGroups:
  - kube-botblocker.github.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kube-botblocker.github.io
  resources:
  - ingresses/finalizers
  verbs:
  - update
- apiGroups:
  - kube-botblocker.github.io
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullName }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-botblocker-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
