{{- if .Values.rbac.enabled }}
{{ $kind := "" }}
{{ $kindBinding := "" }}
{{- if .Values.currentNamespaceOnly }}
{{- $kind        = "Role" }}
{{- $kindBinding = "RoleBinding" }}
{{- else }}
{{- $kind        = "ClusterRole" }}
{{- $kindBinding = "ClusterRoleBinding" }}
{{- end }}
{{- $fullName := include "kube-botblocker-operator.fullname" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $kind }}
metadata:
  labels:
    {{- include "kube-botblocker-operator.labels" . | nindent 4 }}
  name: {{ $fullName }}
rules:
- apiGroups:
  - kube-botblocker.github.io
  resources:
    - ingressconfigs
  verbs:
    - get
    - list
    - watch
    - update
    - patch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ $kindBinding }}
metadata:
  labels:
    {{- include "kube-botblocker-operator.labels" . | nindent 4 }}
  name: {{ $fullName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ $kind }}
  name: {{ $fullName }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-botblocker-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
