apiVersion: kube-botblocker.github.io/v1alpha1
kind: IngressConfig
metadata:
  labels:
    app.kubernetes.io/name: kube-botblocker
    app.kubernetes.io/managed-by: kustomize
  name: ingressconfig-sample
spec:
  blockedUserAgents:
    - AI2Bot
    - GoogleBot
    - AI2Bot
    - Ai2Bot-Dolma
    - Amazonbot
    - anthropic-ai
    - Applebot
    - Applebot-Extended
    - Bytespider
    - CCBot
    - ChatGPT-User
    - Claude-Web
    - ClaudeBot
    - cohere-ai
    - Diffbot
    - DuckAssistBot
    - FacebookBot
    - facebookexternalhit
    - FriendlyCrawler
    - Google-Extended
    - GoogleOther
    - GoogleOther-Image
    - GoogleOther-Video
    - GPTBot
    - iaskspider/2.0
    - ICCCrawler
    - ImagesiftBot
    - img2dataset
    - ISSCyberRiskCrawler
    - KangarooBot
    - Meta-ExternalAgent
    - Meta-ExternalFetcher
    - OAI-SearchBot
    - omgili
    - omgilibot
    - PerplexityBot
    - PetalBot
    - Scrapy
    - SidetradeIndexerBot
    - Timpibot
    - VelenPublicWebCrawler
    - Webzio-Extended
    - YouBot
    - AhrefsBot
    - SemrushBot
    - meta-externalagent
