apiVersion: v2
name: kube-botblocker-operator
description: Easily configure User-Agent blocks for selected ingresses - ingress-nginx only
type: application
version: 0.2.1
appVersion: "0.2.0"
home: https://gustavojst.github.io/kube-botblocker
sources:
  - https://github.com/GustavoJST/kube-botblocker
keywords:
  - bots
  - user-agent
  - block
  - ingress
  - nginx
kubeVersion: ">=1.26.0-0"
maintainers:
  - name: GustavoJST
    email: gustavo.justo@outlook.com
annotations:
  artifacthub.io/operator: "true"
  artifacthub.io/links: |
    - name: "Chart source and upstream project"
      url: https://github.com/GustavoJST/kube-botblocker


dependencies:
  - name: kube-botblocker-operator-crds
    version: "0.2.1"
    condition: crds.enabled
    repository: file://../kube-botblocker-operator-crds